### ISSUE TITLE
[Todo] Cleanup package.json

### ISSUE THREAD

**Issue by mrjvs** [JamesHawkinss/movie-web#73]
package.json has a bunch of small issues that stack up:
 - [ ] Move all types to dev dependencies
 - [ ] update react-router to latest version
 - [ ] fix react-router imports to actual packages that are installed
 - [ ] regenerate lock file
 - [ ] remove testing dependencies (we dont use them)

Some of these are have the side-effect that `npm i` doesn't work. only yarn works.
